### PR TITLE
Fixed typo in README.md and added extra with small refactoring/enhancements

### PR DESCRIPTION
**Pull request by Ajay9o9**
Updated README.md file with following changes

1. Fixed typo
2. Added additional links to point to clean-architecture
3. Readme enhancements

### CODE REVIEW

**Comment by jigarfumakiya** [comment]
Hey, @Ajay9o9 Please point PR to Dev-0.0.5 also could you please fix conflicts?

**Comment by Ajay9o9** [comment]
> Hey, @Ajay9o9 Please point PR to Dev-0.0.5 also could you please fix conflicts?

@jigarfumakiya done

**Comment by Ajay9o9** [comment]
@jigarfumakiya i have resolved the conflicts.

**Comment by jigarfumakiya** [comment]
Thanks, @Ajay9o9 But create PR that points to the dev-0.0.5 branch not the main.

**Pull request merged**
